import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Tab from "@mui/material/Tab";
import Tabs from "@mui/material/Tabs";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import LoginFooter from "../LoginFooter";
import LoginHeader from "../LoginHeader";
import Login from "../LoginPanel";
import RegistrationLottie from "../registration-lottie";
import Registration from "../RegistrationPanel";
import styles from "./welcomePanel.module.css";
import ETTMSText from "/public/locals";

export default function WelcomePanel() {
  const router = useRouter();
  const [selectedTab, setSelectedTab] = useState(0);
  const { locale } = useRouter();

  useEffect(() => {
    const tab =
      router.query.tab === "login"
        ? 0
        : router.query.tab === "registration"
        ? 1
        : 0;
    setSelectedTab(tab);
  }, [router]);

  const handleTabChange = (event, newValue) => {
    if (newValue === 0) {
      router.push("/?tab=login", undefined, { shallow: true });
    } else {
      router.push("/?tab=registration", undefined, { shallow: true });
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["welcome-panel-wrapper"]}>
        <LoginHeader />
        {/* <button onClick={() => gotToHome()}>GO TO HOME</button> */}

        <Grid container justifyContent="center" spacing={3} mt={1}>
          <Grid
            item
            sm={{ display: "none" }}
            md={4}
            className={styles["registration-lottie-wrapper"]}
          >
            <RegistrationLottie />
          </Grid>
          {/* <Divider orientation="vertical" variant="middle" flexItem /> */}
          <Grid item md={4} sx={12}>
            {/* <Item> */}
            <Box
              sx={{
                width: "50vw",
                bgcolor: "background.paper",
                marginBottom: "1rem",
                marginTop: "0rem",
              }}
            >
              <Tabs value={selectedTab} onChange={handleTabChange} centered>
                <Tab label={ETTMSText[locale].welcomePage.login.loginTitle} />
                <Tab
                  label={
                    ETTMSText[locale].welcomePage.registration.registrationTitle
                  }
                />
                {/* <Tab label="Item Three" /> */}
              </Tabs>
            </Box>
            <Box
              sx={{ width: "100%" }}
              className={styles["welcome-login-reg-side-wrapper"]}
            >
              {router.query.tab === "login" ? (
                <Login />
              ) : router.query.tab === "registration" ? (
                <Registration />
              ) : (
                <Login />
              )}
            </Box>

            {/* </Item> */}
          </Grid>
        </Grid>
        <LoginFooter />
      </div>
    </>
  );
}
