import Head from "next/head";
import lottie from "lottie-web";
import React, { useEffect, useRef } from "react";
import styles from "./404.module.css";

const RegistrationLottie = () => {
  const container = useRef(null);

  useEffect(() => {
    lottie.loadAnimation({
      container: container.current,
      renderer: "svg",
      loop: true,
      autoplay: true,
      animationData: require("/public/404LottieAnimation/404.json"),
    });
  }, []);
  return (
    <>
    <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <div className={styles["notFoundPage-wrapper"]} ref={container}></div>{" "}
    </div>
    </>
  );
};

export default RegistrationLottie;
