import Head from 'next/head';
import Welcome from '../components/welcomeComponents/WelcomePanel';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome/>
    </>

      
  )
}
